// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteMusicByIdCoverData, DeleteMusicByIdCoverErrors, DeleteMusicByIdCoverResponses, DeleteMusicByIdData, DeleteMusicByIdErrors, DeleteMusicByIdResponses, DeletePlaylistsByIdData, DeletePlaylistsByIdErrors, DeletePlaylistsByIdResponses, DeletePlaylistsByIdTracksByTrackIdData, DeletePlaylistsByIdTracksByTrackIdErrors, DeletePlaylistsByIdTracksByTrackIdResponses, GetMusicByIdCoverData, GetMusicByIdCoverErrors, GetMusicByIdCoverResponses, GetMusicByIdCoverThumbData, GetMusicByIdCoverThumbErrors, GetMusicByIdCoverThumbResponses, GetMusicByIdDownloadData, GetMusicByIdDownloadErrors, GetMusicByIdDownloadResponses, GetMusicData, GetMusicImportsByIdData, GetMusicImportsByIdErrors, GetMusicImportsByIdResponses, GetMusicResponses, GetPlaylistsByIdData, GetPlaylistsByIdErrors, GetPlaylistsByIdResponses, GetPlaylistsData, GetPlaylistsResponses, PatchMusicByIdData, PatchMusicByIdErrors, PatchMusicByIdResponses, PatchPlaylistsByIdData, PatchPlaylistsByIdErrors, PatchPlaylistsByIdResponses, PatchPlaylistsByIdTracksReorderData, PatchPlaylistsByIdTracksReorderErrors, PatchPlaylistsByIdTracksReorderResponses, PostMusicByIdCoverData, PostMusicByIdCoverErrors, PostMusicByIdCoverResponses, PostMusicData, PostMusicErrors, PostMusicImportsData, PostMusicImportsErrors, PostMusicImportsParseUrlData, PostMusicImportsParseUrlErrors, PostMusicImportsParseUrlResponses, PostMusicImportsResponses, PostMusicImportsSearchData, PostMusicImportsSearchErrors, PostMusicImportsSearchResponses, PostMusicResponses, PostPlaylistsByIdTracksData, PostPlaylistsByIdTracksErrors, PostPlaylistsByIdTracksResponses, PostPlaylistsData, PostPlaylistsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List uploaded music metadata
 */
export const getMusic = <ThrowOnError extends boolean = false>(options?: Options<GetMusicData, ThrowOnError>) => (options?.client ?? client).get<GetMusicResponses, unknown, ThrowOnError>({ url: '/music', ...options });

/**
 * Upload a music file
 */
export const postMusic = <ThrowOnError extends boolean = false>(options?: Options<PostMusicData, ThrowOnError>) => (options?.client ?? client).post<PostMusicResponses, PostMusicErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/music',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * Search tracks through musicdl
 */
export const postMusicImportsSearch = <ThrowOnError extends boolean = false>(options?: Options<PostMusicImportsSearchData, ThrowOnError>) => (options?.client ?? client).post<PostMusicImportsSearchResponses, PostMusicImportsSearchErrors, ThrowOnError>({
    url: '/music/imports/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Resolve a Bilibili or Youtube URL into an importable candidate
 */
export const postMusicImportsParseUrl = <ThrowOnError extends boolean = false>(options?: Options<PostMusicImportsParseUrlData, ThrowOnError>) => (options?.client ?? client).post<PostMusicImportsParseUrlResponses, PostMusicImportsParseUrlErrors, ThrowOnError>({
    url: '/music/imports/parse-url',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Create an asynchronous import job through musicdl
 */
export const postMusicImports = <ThrowOnError extends boolean = false>(options?: Options<PostMusicImportsData, ThrowOnError>) => (options?.client ?? client).post<PostMusicImportsResponses, PostMusicImportsErrors, ThrowOnError>({
    url: '/music/imports',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get an import job status
 */
export const getMusicImportsById = <ThrowOnError extends boolean = false>(options: Options<GetMusicImportsByIdData, ThrowOnError>) => (options.client ?? client).get<GetMusicImportsByIdResponses, GetMusicImportsByIdErrors, ThrowOnError>({ url: '/music/imports/{id}', ...options });

/**
 * List playlists
 */
export const getPlaylists = <ThrowOnError extends boolean = false>(options?: Options<GetPlaylistsData, ThrowOnError>) => (options?.client ?? client).get<GetPlaylistsResponses, unknown, ThrowOnError>({ url: '/playlists', ...options });

/**
 * Create a playlist
 */
export const postPlaylists = <ThrowOnError extends boolean = false>(options?: Options<PostPlaylistsData, ThrowOnError>) => (options?.client ?? client).post<PostPlaylistsResponses, unknown, ThrowOnError>({
    url: '/playlists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a playlist
 */
export const deletePlaylistsById = <ThrowOnError extends boolean = false>(options: Options<DeletePlaylistsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeletePlaylistsByIdResponses, DeletePlaylistsByIdErrors, ThrowOnError>({ url: '/playlists/{id}', ...options });

/**
 * Get a playlist
 */
export const getPlaylistsById = <ThrowOnError extends boolean = false>(options: Options<GetPlaylistsByIdData, ThrowOnError>) => (options.client ?? client).get<GetPlaylistsByIdResponses, GetPlaylistsByIdErrors, ThrowOnError>({ url: '/playlists/{id}', ...options });

/**
 * Update a playlist
 */
export const patchPlaylistsById = <ThrowOnError extends boolean = false>(options: Options<PatchPlaylistsByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchPlaylistsByIdResponses, PatchPlaylistsByIdErrors, ThrowOnError>({
    url: '/playlists/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add a track to a playlist
 */
export const postPlaylistsByIdTracks = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistsByIdTracksData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistsByIdTracksResponses, PostPlaylistsByIdTracksErrors, ThrowOnError>({
    url: '/playlists/{id}/tracks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reorder playlist tracks
 */
export const patchPlaylistsByIdTracksReorder = <ThrowOnError extends boolean = false>(options: Options<PatchPlaylistsByIdTracksReorderData, ThrowOnError>) => (options.client ?? client).patch<PatchPlaylistsByIdTracksReorderResponses, PatchPlaylistsByIdTracksReorderErrors, ThrowOnError>({
    url: '/playlists/{id}/tracks/reorder',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a track from a playlist
 */
export const deletePlaylistsByIdTracksByTrackId = <ThrowOnError extends boolean = false>(options: Options<DeletePlaylistsByIdTracksByTrackIdData, ThrowOnError>) => (options.client ?? client).delete<DeletePlaylistsByIdTracksByTrackIdResponses, DeletePlaylistsByIdTracksByTrackIdErrors, ThrowOnError>({ url: '/playlists/{id}/tracks/{trackId}', ...options });

/**
 * Remove a track cover
 */
export const deleteMusicByIdCover = <ThrowOnError extends boolean = false>(options: Options<DeleteMusicByIdCoverData, ThrowOnError>) => (options.client ?? client).delete<DeleteMusicByIdCoverResponses, DeleteMusicByIdCoverErrors, ThrowOnError>({ url: '/music/{id}/cover', ...options });

/**
 * Get a track cover by id
 */
export const getMusicByIdCover = <ThrowOnError extends boolean = false>(options: Options<GetMusicByIdCoverData, ThrowOnError>) => (options.client ?? client).get<GetMusicByIdCoverResponses, GetMusicByIdCoverErrors, ThrowOnError>({ url: '/music/{id}/cover', ...options });

/**
 * Upload a new cover image for a track
 */
export const postMusicByIdCover = <ThrowOnError extends boolean = false>(options: Options<PostMusicByIdCoverData, ThrowOnError>) => (options.client ?? client).post<PostMusicByIdCoverResponses, PostMusicByIdCoverErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/music/{id}/cover',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get a track cover thumbnail by id
 */
export const getMusicByIdCoverThumb = <ThrowOnError extends boolean = false>(options: Options<GetMusicByIdCoverThumbData, ThrowOnError>) => (options.client ?? client).get<GetMusicByIdCoverThumbResponses, GetMusicByIdCoverThumbErrors, ThrowOnError>({ url: '/music/{id}/cover/thumb', ...options });

/**
 * Download a music file by id
 */
export const getMusicByIdDownload = <ThrowOnError extends boolean = false>(options: Options<GetMusicByIdDownloadData, ThrowOnError>) => (options.client ?? client).get<GetMusicByIdDownloadResponses, GetMusicByIdDownloadErrors, ThrowOnError>({ url: '/music/{id}/download', ...options });

/**
 * Delete a music file
 */
export const deleteMusicById = <ThrowOnError extends boolean = false>(options: Options<DeleteMusicByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteMusicByIdResponses, DeleteMusicByIdErrors, ThrowOnError>({ url: '/music/{id}', ...options });

/**
 * Update editable track metadata (title/artists/album/source/lyrics)
 */
export const patchMusicById = <ThrowOnError extends boolean = false>(options: Options<PatchMusicByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchMusicByIdResponses, PatchMusicByIdErrors, ThrowOnError>({
    url: '/music/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
