// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteMusicByIdData, DeleteMusicByIdErrors, DeleteMusicByIdResponses, GetMusicByIdDownloadData, GetMusicByIdDownloadErrors, GetMusicByIdDownloadResponses, GetMusicData, GetMusicImportsByIdData, GetMusicImportsByIdErrors, GetMusicImportsByIdResponses, GetMusicResponses, PostMusicData, PostMusicErrors, PostMusicImportsData, PostMusicImportsErrors, PostMusicImportsResponses, PostMusicImportsSearchData, PostMusicImportsSearchErrors, PostMusicImportsSearchResponses, PostMusicResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List uploaded music metadata
 */
export const getMusic = <ThrowOnError extends boolean = false>(options?: Options<GetMusicData, ThrowOnError>) => (options?.client ?? client).get<GetMusicResponses, unknown, ThrowOnError>({ url: '/music', ...options });

/**
 * Upload a music file
 */
export const postMusic = <ThrowOnError extends boolean = false>(options?: Options<PostMusicData, ThrowOnError>) => (options?.client ?? client).post<PostMusicResponses, PostMusicErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/music',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * Search tracks through musicdl
 */
export const postMusicImportsSearch = <ThrowOnError extends boolean = false>(options?: Options<PostMusicImportsSearchData, ThrowOnError>) => (options?.client ?? client).post<PostMusicImportsSearchResponses, PostMusicImportsSearchErrors, ThrowOnError>({
    url: '/music/imports/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Create an asynchronous import job through musicdl
 */
export const postMusicImports = <ThrowOnError extends boolean = false>(options?: Options<PostMusicImportsData, ThrowOnError>) => (options?.client ?? client).post<PostMusicImportsResponses, PostMusicImportsErrors, ThrowOnError>({
    url: '/music/imports',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get an import job status
 */
export const getMusicImportsById = <ThrowOnError extends boolean = false>(options: Options<GetMusicImportsByIdData, ThrowOnError>) => (options.client ?? client).get<GetMusicImportsByIdResponses, GetMusicImportsByIdErrors, ThrowOnError>({ url: '/music/imports/{id}', ...options });

/**
 * Download a music file by id
 */
export const getMusicByIdDownload = <ThrowOnError extends boolean = false>(options: Options<GetMusicByIdDownloadData, ThrowOnError>) => (options.client ?? client).get<GetMusicByIdDownloadResponses, GetMusicByIdDownloadErrors, ThrowOnError>({ url: '/music/{id}/download', ...options });

/**
 * Delete a music file
 */
export const deleteMusicById = <ThrowOnError extends boolean = false>(options: Options<DeleteMusicByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteMusicByIdResponses, DeleteMusicByIdErrors, ThrowOnError>({ url: '/music/{id}', ...options });
