// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type Music = {
    id: string;
    filename: string;
    size: number;
    contentType: string | null;
    coverUrl: string | null;
    lyrics: string | null;
    title: string | null;
    artists: string | null;
    album: string | null;
    source: string | null;
    sourceIdentifier: string | null;
    durationText: string | null;
    durationSeconds: number | null;
    createdAt: string;
};

export type MusicDlSearchResult = {
    id: string;
    songName: string;
    singers: string;
    album: string;
    source: string;
    sourceIdentifier: string | null;
    ext: string;
    fileSize: string;
    duration: string;
    coverUrl: string;
    downloadable: boolean;
};

export type MusicDlSource = 'NeteaseMusicClient' | 'QQMusicClient' | 'KuwoMusicClient' | 'MiguMusicClient' | 'JamendoMusicClient';

export type MusicDlSearchRequest = {
    keyword: string;
    source?: MusicDlSource;
    limitPerSource?: number;
};

export type MusicImportJob = {
    id: string;
    source: string;
    songName: string;
    singers: string;
    status: 'queued' | 'running' | 'succeeded' | 'failed';
    trackId: string | null;
    errorMessage: string | null;
    progressBytes: number | null;
    totalBytes: number | null;
    progressPercent: number | null;
    createdAt: string;
    updatedAt: string;
    startedAt: string | null;
    finishedAt: string | null;
};

export type MusicDlImportRequest = {
    resultId: string;
};

export type GetMusicData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/music';
};

export type GetMusicResponses = {
    /**
     * List of music files
     */
    200: Array<Music>;
};

export type GetMusicResponse = GetMusicResponses[keyof GetMusicResponses];

export type PostMusicData = {
    body?: {
        /**
         * Audio file to store
         */
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/music';
};

export type PostMusicErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostMusicError = PostMusicErrors[keyof PostMusicErrors];

export type PostMusicResponses = {
    /**
     * Created
     */
    201: Music;
};

export type PostMusicResponse = PostMusicResponses[keyof PostMusicResponses];

export type PostMusicImportsSearchData = {
    body?: MusicDlSearchRequest;
    path?: never;
    query?: never;
    url: '/music/imports/search';
};

export type PostMusicImportsSearchErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsSearchError = PostMusicImportsSearchErrors[keyof PostMusicImportsSearchErrors];

export type PostMusicImportsSearchResponses = {
    /**
     * Search results
     */
    200: Array<MusicDlSearchResult>;
};

export type PostMusicImportsSearchResponse = PostMusicImportsSearchResponses[keyof PostMusicImportsSearchResponses];

export type PostMusicImportsData = {
    body?: MusicDlImportRequest;
    path?: never;
    query?: never;
    url: '/music/imports';
};

export type PostMusicImportsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Search result not found
     */
    404: {
        message: string;
    };
};

export type PostMusicImportsError = PostMusicImportsErrors[keyof PostMusicImportsErrors];

export type PostMusicImportsResponses = {
    /**
     * Accepted
     */
    202: MusicImportJob;
};

export type PostMusicImportsResponse = PostMusicImportsResponses[keyof PostMusicImportsResponses];

export type GetMusicImportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/imports/{id}';
};

export type GetMusicImportsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicImportsByIdError = GetMusicImportsByIdErrors[keyof GetMusicImportsByIdErrors];

export type GetMusicImportsByIdResponses = {
    /**
     * Job status
     */
    200: MusicImportJob;
};

export type GetMusicImportsByIdResponse = GetMusicImportsByIdResponses[keyof GetMusicImportsByIdResponses];

export type GetMusicByIdDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/download';
};

export type GetMusicByIdDownloadErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdDownloadError = GetMusicByIdDownloadErrors[keyof GetMusicByIdDownloadErrors];

export type GetMusicByIdDownloadResponses = {
    /**
     * Audio stream
     */
    200: Blob | File;
};

export type GetMusicByIdDownloadResponse = GetMusicByIdDownloadResponses[keyof GetMusicByIdDownloadResponses];

export type DeleteMusicByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}';
};

export type DeleteMusicByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdError = DeleteMusicByIdErrors[keyof DeleteMusicByIdErrors];

export type DeleteMusicByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteMusicByIdResponse = DeleteMusicByIdResponses[keyof DeleteMusicByIdResponses];
