// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type Music = {
    id: string;
    filename: string;
    size: number;
    contentType: string;
    coverUrl: string;
    coverThumbUrl: string;
    lyrics: string;
    title: string;
    artists: string;
    album: string;
    source: string;
    sourceIdentifier: string;
    durationText: string;
    durationSeconds: number;
    createdAt: string;
};

export type MusicDlSearchResult = {
    id: string;
    songName: string;
    singers: string;
    album: string;
    source: string;
    sourceIdentifier: string;
    ext: string;
    fileSize: string;
    duration: string;
    coverUrl: string;
    downloadable: boolean;
};

export type MusicDlSearchRequest = {
    keyword: string;
    source?: MusicDlSource;
    limitPerSource?: number;
};

export type MusicDlSource = 'NeteaseMusicClient' | 'QQMusicClient' | 'KuwoMusicClient' | 'MiguMusicClient' | 'JamendoMusicClient';

export type MusicDlParseUrlRequest = {
    url: string;
};

export type MusicImportJob = {
    id: string;
    source: string;
    songName: string;
    singers: string;
    status: 'queued' | 'running' | 'succeeded' | 'failed';
    trackId: string;
    errorMessage: string;
    progressBytes: number;
    totalBytes: number;
    progressPercent: number;
    createdAt: string;
    updatedAt: string;
    startedAt: string;
    finishedAt: string;
};

export type MusicDlImportRequest = {
    resultId: string;
};

export type UpdateMusicRequest = {
    title?: string;
    artists?: string;
    album?: string;
    source?: string;
    lyrics?: string;
};

export type GetMusicData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/music';
};

export type GetMusicResponses = {
    /**
     * List of music files
     */
    200: Array<Music>;
};

export type GetMusicResponse = GetMusicResponses[keyof GetMusicResponses];

export type PostMusicData = {
    body?: {
        /**
         * Audio file to store
         */
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/music';
};

export type PostMusicErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostMusicError = PostMusicErrors[keyof PostMusicErrors];

export type PostMusicResponses = {
    /**
     * Created
     */
    201: Music;
};

export type PostMusicResponse = PostMusicResponses[keyof PostMusicResponses];

export type PostMusicImportsSearchData = {
    body?: MusicDlSearchRequest;
    path?: never;
    query?: never;
    url: '/music/imports/search';
};

export type PostMusicImportsSearchErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsSearchError = PostMusicImportsSearchErrors[keyof PostMusicImportsSearchErrors];

export type PostMusicImportsSearchResponses = {
    /**
     * Search results
     */
    200: Array<MusicDlSearchResult>;
};

export type PostMusicImportsSearchResponse = PostMusicImportsSearchResponses[keyof PostMusicImportsSearchResponses];

export type PostMusicImportsParseUrlData = {
    body?: MusicDlParseUrlRequest;
    path?: never;
    query?: never;
    url: '/music/imports/parse-url';
};

export type PostMusicImportsParseUrlErrors = {
    /**
     * Invalid URL
     */
    400: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsParseUrlError = PostMusicImportsParseUrlErrors[keyof PostMusicImportsParseUrlErrors];

export type PostMusicImportsParseUrlResponses = {
    /**
     * Parsed result
     */
    200: MusicDlSearchResult;
};

export type PostMusicImportsParseUrlResponse = PostMusicImportsParseUrlResponses[keyof PostMusicImportsParseUrlResponses];

export type PostMusicImportsData = {
    body?: MusicDlImportRequest;
    path?: never;
    query?: never;
    url: '/music/imports';
};

export type PostMusicImportsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Search result not found
     */
    404: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsError = PostMusicImportsErrors[keyof PostMusicImportsErrors];

export type PostMusicImportsResponses = {
    /**
     * Accepted
     */
    202: MusicImportJob;
};

export type PostMusicImportsResponse = PostMusicImportsResponses[keyof PostMusicImportsResponses];

export type GetMusicImportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/imports/{id}';
};

export type GetMusicImportsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicImportsByIdError = GetMusicImportsByIdErrors[keyof GetMusicImportsByIdErrors];

export type GetMusicImportsByIdResponses = {
    /**
     * Job status
     */
    200: MusicImportJob;
};

export type GetMusicImportsByIdResponse = GetMusicImportsByIdResponses[keyof GetMusicImportsByIdResponses];

export type DeleteMusicByIdCoverData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type DeleteMusicByIdCoverErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdCoverError = DeleteMusicByIdCoverErrors[keyof DeleteMusicByIdCoverErrors];

export type DeleteMusicByIdCoverResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type DeleteMusicByIdCoverResponse = DeleteMusicByIdCoverResponses[keyof DeleteMusicByIdCoverResponses];

export type GetMusicByIdCoverData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type GetMusicByIdCoverErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdCoverError = GetMusicByIdCoverErrors[keyof GetMusicByIdCoverErrors];

export type GetMusicByIdCoverResponses = {
    /**
     * Cover image
     */
    200: Blob | File;
};

export type GetMusicByIdCoverResponse = GetMusicByIdCoverResponses[keyof GetMusicByIdCoverResponses];

export type PostMusicByIdCoverData = {
    body?: {
        /**
         * Cover image file
         */
        file?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type PostMusicByIdCoverErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostMusicByIdCoverError = PostMusicByIdCoverErrors[keyof PostMusicByIdCoverErrors];

export type PostMusicByIdCoverResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type PostMusicByIdCoverResponse = PostMusicByIdCoverResponses[keyof PostMusicByIdCoverResponses];

export type GetMusicByIdCoverThumbData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover/thumb';
};

export type GetMusicByIdCoverThumbErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdCoverThumbError = GetMusicByIdCoverThumbErrors[keyof GetMusicByIdCoverThumbErrors];

export type GetMusicByIdCoverThumbResponses = {
    /**
     * Cover thumbnail image
     */
    200: Blob | File;
};

export type GetMusicByIdCoverThumbResponse = GetMusicByIdCoverThumbResponses[keyof GetMusicByIdCoverThumbResponses];

export type GetMusicByIdDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/download';
};

export type GetMusicByIdDownloadErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdDownloadError = GetMusicByIdDownloadErrors[keyof GetMusicByIdDownloadErrors];

export type GetMusicByIdDownloadResponses = {
    /**
     * Audio stream
     */
    200: Blob | File;
};

export type GetMusicByIdDownloadResponse = GetMusicByIdDownloadResponses[keyof GetMusicByIdDownloadResponses];

export type DeleteMusicByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}';
};

export type DeleteMusicByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdError = DeleteMusicByIdErrors[keyof DeleteMusicByIdErrors];

export type DeleteMusicByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteMusicByIdResponse = DeleteMusicByIdResponses[keyof DeleteMusicByIdResponses];

export type PatchMusicByIdData = {
    body?: UpdateMusicRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}';
};

export type PatchMusicByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchMusicByIdError = PatchMusicByIdErrors[keyof PatchMusicByIdErrors];

export type PatchMusicByIdResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type PatchMusicByIdResponse = PatchMusicByIdResponses[keyof PatchMusicByIdResponses];
