// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Music = {
    id: string;
    filename: string;
    size: number;
    contentType: string | null;
    coverUrl: string | null;
    coverThumbUrl: string | null;
    coverThumbhash: string | null;
    lyrics: string | null;
    /**
     * The lyrics have been edited into a document, fetched from /music/{id}/lyrics; otherwise `lyrics` is the whole of them
     */
    hasLyricsDoc: boolean;
    /**
     * A vocal analysis is stored, fetched from /music/{id}/vocals
     */
    hasVocals: boolean;
    title: string | null;
    artists: string | null;
    album: string | null;
    source: string | null;
    sourceIdentifier: string | null;
    durationText: string | null;
    durationSeconds: number | null;
    /**
     * Ids of playlists this track is part of
     */
    playlistIds: Array<string>;
    /**
     * Counted plays (see play rule on POST /music/{id}/plays)
     */
    playCount: number;
    /**
     * Sessions skipped before the play threshold
     */
    skipCount: number;
    /**
     * Total seconds actually listened (excludes paused time and seeked-over ranges)
     */
    listenedSeconds: number;
    lastPlayedAt: string | null;
    createdAt: string;
};

export type MusicDlSearchResult = {
    id: string;
    songName: string;
    singers: string;
    album: string;
    source: string;
    sourceIdentifier: string | null;
    ext: string;
    fileSize: string;
    duration: string;
    coverUrl: string | null;
    downloadable: boolean;
};

export type MusicDlSearchRequest = {
    keyword: string;
    source?: MusicDlSource;
    limitPerSource?: number;
};

export type MusicDlSource = 'NeteaseMusicClient' | 'QQMusicClient' | 'KuwoMusicClient' | 'MiguMusicClient' | 'JamendoMusicClient';

export type MusicDlParseUrlRequest = {
    url: string;
};

export type MusicImportJob = {
    id: string;
    source: string;
    songName: string;
    singers: string;
    status: 'queued' | 'running' | 'succeeded' | 'failed';
    trackId: string | null;
    errorMessage: string | null;
    progressBytes: number | null;
    totalBytes: number | null;
    progressPercent: number | null;
    createdAt: string;
    updatedAt: string;
    startedAt: string | null;
    finishedAt: string | null;
};

export type MusicDlImportRequest = {
    resultId: string;
};

export type Playlist = {
    id: string;
    name: string;
    description: string | null;
    trackCount: number;
    totalDurationSeconds: number;
    previewCoverUrls: Array<string>;
    previewCoverThumbhashes: Array<string | null>;
    createdAt: string;
    updatedAt: string;
};

export type PlaylistDetail = Playlist & {
    tracks: Array<Music>;
};

export type PlaylistInput = {
    name: string;
    description?: string | null;
};

export type PlaylistTrackInput = {
    trackId: string;
};

export type PlaylistReorderRequest = {
    trackIds: Array<string>;
};

export type LyricsFurigana = {
    /**
     * Furigana segments keyed by cue id
     */
    lines: {
        [key: string]: Array<RubySegment>;
    };
};

export type RubySegment = {
    text: string;
    ruby?: string;
    /**
     * The reading was set by hand rather than analyzed
     */
    explicit?: boolean;
};

export type Lyrics = {
    doc: LyricsDoc | null;
};

export type LyricsDoc = {
    version: 1;
    timing: 'none' | 'line' | 'word';
    lang?: string;
    cues: Array<LyricsCue>;
    tracks: Array<LyricsTrack>;
};

export type LyricsCue = {
    id: string;
    begin?: number;
    end?: number;
    /**
     * Singer for duets, as TTML ttm:agent (v1, v2, …)
     */
    agent?: string;
    words: Array<LyricsWord>;
    /**
     * Backing vocals sung over this cue
     */
    background?: Array<LyricsWord>;
    ruby?: Array<LyricsRuby>;
};

export type LyricsWord = {
    text: string;
    begin?: number;
    end?: number;
};

/**
 * A hand-set reading over cue text [start, end); unset ranges are read by the analyzer
 */
export type LyricsRuby = {
    start: number;
    end: number;
    reading: string;
};

export type LyricsTrack = {
    lang: string;
    kind: 'translation' | 'transliteration';
    /**
     * Text keyed by cue id
     */
    lines: {
        [key: string]: string;
    };
};

export type UpdateMusicRequest = {
    title?: string | null;
    artists?: string | null;
    album?: string | null;
    source?: string | null;
    /**
     * LRC, plain text, or TTML, which is stored as a lyrics document
     */
    lyrics?: string | null;
};

export type MusicReorderRequest = {
    orderedIds: Array<string>;
};

export type AppConfig = {
    api: {
        port: number;
    };
    metadata: {
        backend: 'sqlite';
        dbPath: string;
    } | {
        backend: 'd1';
        accountId: string;
        databaseId: string;
    };
    storage: {
        backend: 'fs';
        rootDir: string;
    } | {
        backend: 's3';
        bucket: string;
        endpoint: string | null;
        region: string;
        forcePathStyle: boolean;
        accessKeyConfigured: boolean;
        secretKeyConfigured: boolean;
    };
    ai: {
        defaultProvider: string;
        providers: {
            [key: string]: {
                apiKeyEnvName: string;
                apiKeyConfigured: boolean;
                apiKeySource: 'environment' | 'settings' | null;
                defaultModel: string | null;
                baseUrl: string | null;
            };
        };
    };
    musicdl: {
        sources: Array<MusicDlSource>;
        urlSources: Array<MusicDlUrlSource>;
        searchTimeoutMs: number;
        downloadTimeoutMs: number;
    };
    imports: {
        candidateTtlMs: number;
        workerPollMs: number;
    };
};

export type MusicDlUrlSource = 'Bilibili' | 'Youtube';

export type AppConfigUpdateResponse = {
    config: AppConfig;
    restartRequired: boolean;
};

export type AppConfigUpdate = {
    metadata?: {
        dbPath?: string;
    };
    storage?: {
        backend: 'fs';
        rootDir: string;
    } | {
        backend: 's3';
        bucket: string;
        endpoint?: string | null;
        region: string;
        accessKeyId?: string;
        secretAccessKey?: string;
    };
    ai?: {
        defaultProvider?: string;
        providers?: {
            [key: string]: {
                apiKey?: string;
                removeApiKey?: boolean;
                defaultModel?: string;
                baseUrl?: string | null;
            };
        };
    };
    musicdl?: {
        sources?: Array<MusicDlSource>;
        urlSources?: Array<MusicDlUrlSource>;
        searchTimeoutMs?: number;
        downloadTimeoutMs?: number;
    };
    imports?: {
        candidateTtlMs?: number;
        workerPollMs?: number;
    };
};

export type PlayEventResponse = {
    /**
     * Whether this session counts as a play
     */
    counted: boolean;
    finalized: boolean;
};

export type PlayEventRequest = {
    /**
     * Client-generated id of this listening session; repeated reports update the same session
     */
    sessionId: string;
    startedAt: string;
    /**
     * Seconds actually heard in this session (paused time and seeked-over ranges excluded)
     */
    listenedSeconds: number;
    durationSeconds?: number | null;
    /**
     * `playing` is a progress checkpoint; `ended` (played to the end), `skipped` (user moved on) and `stopped` (page closed) finalize the session
     */
    status: 'playing' | 'ended' | 'skipped' | 'stopped';
};

export type ListeningStats = {
    totals: {
        playCount: number;
        skipCount: number;
        listenedSeconds: number;
        playedTrackCount: number;
        trackCount: number;
    };
    period: {
        days: number;
        playCount: number;
        listenedSeconds: number;
    };
    daily: Array<{
        /**
         * Local calendar day (per tzOffsetMinutes)
         */
        date: string;
        playCount: number;
        listenedSeconds: number;
    }>;
    topTracks: Array<{
        track: Music;
        playCount: number;
        listenedSeconds: number;
    }>;
    recentPlays: Array<{
        track: Music;
        playedAt: string;
        listenedSeconds: number;
        completed: boolean;
    }>;
};

export type GetMusicData = {
    body?: never;
    path?: never;
    query?: {
        order?: 'default' | 'manual';
    };
    url: '/music';
};

export type GetMusicResponses = {
    /**
     * List of music files
     */
    200: Array<Music>;
};

export type GetMusicResponse = GetMusicResponses[keyof GetMusicResponses];

export type PostMusicData = {
    body?: {
        /**
         * Audio file to store
         */
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/music';
};

export type PostMusicErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostMusicError = PostMusicErrors[keyof PostMusicErrors];

export type PostMusicResponses = {
    /**
     * Created
     */
    201: Music;
};

export type PostMusicResponse = PostMusicResponses[keyof PostMusicResponses];

export type PostMusicUploadsData = {
    body?: {
        filename: string;
        contentType?: string | null;
        size: number;
    };
    path?: never;
    query?: never;
    url: '/music/uploads';
};

export type PostMusicUploadsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * File too large
     */
    413: {
        message: string;
    };
};

export type PostMusicUploadsError = PostMusicUploadsErrors[keyof PostMusicUploadsErrors];

export type PostMusicUploadsResponses = {
    /**
     * Upload session
     */
    201: {
        id: string;
        chunkSize: number;
        chunkCount: number;
    };
};

export type PostMusicUploadsResponse = PostMusicUploadsResponses[keyof PostMusicUploadsResponses];

export type PutMusicUploadsByIdChunksByIndexData = {
    body?: Blob | File;
    path: {
        id: string;
        index?: number | null;
    };
    query?: never;
    url: '/music/uploads/{id}/chunks/{index}';
};

export type PutMusicUploadsByIdChunksByIndexErrors = {
    /**
     * Invalid chunk
     */
    400: {
        message: string;
    };
    /**
     * Upload session not found
     */
    404: {
        message: string;
    };
};

export type PutMusicUploadsByIdChunksByIndexError = PutMusicUploadsByIdChunksByIndexErrors[keyof PutMusicUploadsByIdChunksByIndexErrors];

export type PutMusicUploadsByIdChunksByIndexResponses = {
    /**
     * Chunk stored
     */
    204: void;
};

export type PutMusicUploadsByIdChunksByIndexResponse = PutMusicUploadsByIdChunksByIndexResponses[keyof PutMusicUploadsByIdChunksByIndexResponses];

export type PostMusicUploadsByIdCompleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/uploads/{id}/complete';
};

export type PostMusicUploadsByIdCompleteErrors = {
    /**
     * Upload session not found
     */
    404: {
        message: string;
    };
    /**
     * Chunks are missing
     */
    409: {
        message: string;
    };
};

export type PostMusicUploadsByIdCompleteError = PostMusicUploadsByIdCompleteErrors[keyof PostMusicUploadsByIdCompleteErrors];

export type PostMusicUploadsByIdCompleteResponses = {
    /**
     * Created
     */
    201: Music;
};

export type PostMusicUploadsByIdCompleteResponse = PostMusicUploadsByIdCompleteResponses[keyof PostMusicUploadsByIdCompleteResponses];

export type DeleteMusicUploadsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/uploads/{id}';
};

export type DeleteMusicUploadsByIdResponses = {
    /**
     * Aborted
     */
    204: void;
};

export type DeleteMusicUploadsByIdResponse = DeleteMusicUploadsByIdResponses[keyof DeleteMusicUploadsByIdResponses];

export type PostMusicImportsSearchData = {
    body?: MusicDlSearchRequest;
    path?: never;
    query?: never;
    url: '/music/imports/search';
};

export type PostMusicImportsSearchErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsSearchError = PostMusicImportsSearchErrors[keyof PostMusicImportsSearchErrors];

export type PostMusicImportsSearchResponses = {
    /**
     * Search results
     */
    200: Array<MusicDlSearchResult>;
};

export type PostMusicImportsSearchResponse = PostMusicImportsSearchResponses[keyof PostMusicImportsSearchResponses];

export type PostMusicImportsParseUrlData = {
    body?: MusicDlParseUrlRequest;
    path?: never;
    query?: never;
    url: '/music/imports/parse-url';
};

export type PostMusicImportsParseUrlErrors = {
    /**
     * Invalid URL
     */
    400: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsParseUrlError = PostMusicImportsParseUrlErrors[keyof PostMusicImportsParseUrlErrors];

export type PostMusicImportsParseUrlResponses = {
    /**
     * Parsed result
     */
    200: MusicDlSearchResult;
};

export type PostMusicImportsParseUrlResponse = PostMusicImportsParseUrlResponses[keyof PostMusicImportsParseUrlResponses];

export type PostMusicImportsData = {
    body?: MusicDlImportRequest;
    path?: never;
    query?: never;
    url: '/music/imports';
};

export type PostMusicImportsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Search result not found
     */
    404: {
        message: string;
    };
    /**
     * musicdl failed
     */
    502: {
        message: string;
    };
    /**
     * musicdl unavailable
     */
    503: {
        message: string;
    };
};

export type PostMusicImportsError = PostMusicImportsErrors[keyof PostMusicImportsErrors];

export type PostMusicImportsResponses = {
    /**
     * Accepted
     */
    202: MusicImportJob;
};

export type PostMusicImportsResponse = PostMusicImportsResponses[keyof PostMusicImportsResponses];

export type GetMusicImportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/imports/{id}';
};

export type GetMusicImportsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicImportsByIdError = GetMusicImportsByIdErrors[keyof GetMusicImportsByIdErrors];

export type GetMusicImportsByIdResponses = {
    /**
     * Job status
     */
    200: MusicImportJob;
};

export type GetMusicImportsByIdResponse = GetMusicImportsByIdResponses[keyof GetMusicImportsByIdResponses];

export type GetPlaylistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlists';
};

export type GetPlaylistsResponses = {
    /**
     * List of playlists
     */
    200: Array<Playlist>;
};

export type GetPlaylistsResponse = GetPlaylistsResponses[keyof GetPlaylistsResponses];

export type PostPlaylistsData = {
    body?: PlaylistInput;
    path?: never;
    query?: never;
    url: '/playlists';
};

export type PostPlaylistsResponses = {
    /**
     * Created
     */
    201: PlaylistDetail;
};

export type PostPlaylistsResponse = PostPlaylistsResponses[keyof PostPlaylistsResponses];

export type DeletePlaylistsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/playlists/{id}';
};

export type DeletePlaylistsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeletePlaylistsByIdError = DeletePlaylistsByIdErrors[keyof DeletePlaylistsByIdErrors];

export type DeletePlaylistsByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeletePlaylistsByIdResponse = DeletePlaylistsByIdResponses[keyof DeletePlaylistsByIdResponses];

export type GetPlaylistsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/playlists/{id}';
};

export type GetPlaylistsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetPlaylistsByIdError = GetPlaylistsByIdErrors[keyof GetPlaylistsByIdErrors];

export type GetPlaylistsByIdResponses = {
    /**
     * Playlist detail
     */
    200: PlaylistDetail;
};

export type GetPlaylistsByIdResponse = GetPlaylistsByIdResponses[keyof GetPlaylistsByIdResponses];

export type PatchPlaylistsByIdData = {
    body?: PlaylistInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/playlists/{id}';
};

export type PatchPlaylistsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchPlaylistsByIdError = PatchPlaylistsByIdErrors[keyof PatchPlaylistsByIdErrors];

export type PatchPlaylistsByIdResponses = {
    /**
     * Updated
     */
    200: PlaylistDetail;
};

export type PatchPlaylistsByIdResponse = PatchPlaylistsByIdResponses[keyof PatchPlaylistsByIdResponses];

export type PostPlaylistsByIdTracksData = {
    body?: PlaylistTrackInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/playlists/{id}/tracks';
};

export type PostPlaylistsByIdTracksErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
    /**
     * Track already exists in playlist
     */
    409: {
        message: string;
    };
};

export type PostPlaylistsByIdTracksError = PostPlaylistsByIdTracksErrors[keyof PostPlaylistsByIdTracksErrors];

export type PostPlaylistsByIdTracksResponses = {
    /**
     * Updated playlist
     */
    200: PlaylistDetail;
};

export type PostPlaylistsByIdTracksResponse = PostPlaylistsByIdTracksResponses[keyof PostPlaylistsByIdTracksResponses];

export type PatchPlaylistsByIdTracksReorderData = {
    body?: PlaylistReorderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/playlists/{id}/tracks/reorder';
};

export type PatchPlaylistsByIdTracksReorderErrors = {
    /**
     * Invalid order
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchPlaylistsByIdTracksReorderError = PatchPlaylistsByIdTracksReorderErrors[keyof PatchPlaylistsByIdTracksReorderErrors];

export type PatchPlaylistsByIdTracksReorderResponses = {
    /**
     * Updated playlist
     */
    200: PlaylistDetail;
};

export type PatchPlaylistsByIdTracksReorderResponse = PatchPlaylistsByIdTracksReorderResponses[keyof PatchPlaylistsByIdTracksReorderResponses];

export type DeletePlaylistsByIdTracksByTrackIdData = {
    body?: never;
    path: {
        id: string;
        trackId: string;
    };
    query?: never;
    url: '/playlists/{id}/tracks/{trackId}';
};

export type DeletePlaylistsByIdTracksByTrackIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeletePlaylistsByIdTracksByTrackIdError = DeletePlaylistsByIdTracksByTrackIdErrors[keyof DeletePlaylistsByIdTracksByTrackIdErrors];

export type DeletePlaylistsByIdTracksByTrackIdResponses = {
    /**
     * Updated playlist
     */
    200: PlaylistDetail;
};

export type DeletePlaylistsByIdTracksByTrackIdResponse = DeletePlaylistsByIdTracksByTrackIdResponses[keyof DeletePlaylistsByIdTracksByTrackIdResponses];

export type DeleteMusicByIdCoverData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type DeleteMusicByIdCoverErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdCoverError = DeleteMusicByIdCoverErrors[keyof DeleteMusicByIdCoverErrors];

export type DeleteMusicByIdCoverResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type DeleteMusicByIdCoverResponse = DeleteMusicByIdCoverResponses[keyof DeleteMusicByIdCoverResponses];

export type GetMusicByIdCoverData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type GetMusicByIdCoverErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdCoverError = GetMusicByIdCoverErrors[keyof GetMusicByIdCoverErrors];

export type GetMusicByIdCoverResponses = {
    /**
     * Cover image
     */
    200: Blob | File;
};

export type GetMusicByIdCoverResponse = GetMusicByIdCoverResponses[keyof GetMusicByIdCoverResponses];

export type PostMusicByIdCoverData = {
    body?: {
        /**
         * Cover image file
         */
        file?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover';
};

export type PostMusicByIdCoverErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostMusicByIdCoverError = PostMusicByIdCoverErrors[keyof PostMusicByIdCoverErrors];

export type PostMusicByIdCoverResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type PostMusicByIdCoverResponse = PostMusicByIdCoverResponses[keyof PostMusicByIdCoverResponses];

export type GetMusicByIdCoverThumbData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover/thumb';
};

export type GetMusicByIdCoverThumbErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdCoverThumbError = GetMusicByIdCoverThumbErrors[keyof GetMusicByIdCoverThumbErrors];

export type GetMusicByIdCoverThumbResponses = {
    /**
     * Cover thumbnail image
     */
    200: Blob | File;
};

export type GetMusicByIdCoverThumbResponse = GetMusicByIdCoverThumbResponses[keyof GetMusicByIdCoverThumbResponses];

export type GetMusicByIdCoverMaskData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/cover/mask';
};

export type GetMusicByIdCoverMaskErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdCoverMaskError = GetMusicByIdCoverMaskErrors[keyof GetMusicByIdCoverMaskErrors];

export type GetMusicByIdCoverMaskResponses = {
    /**
     * Cover mask image
     */
    200: Blob | File;
};

export type GetMusicByIdCoverMaskResponse = GetMusicByIdCoverMaskResponses[keyof GetMusicByIdCoverMaskResponses];

export type GetMusicByIdLyricsFuriganaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/lyrics/furigana';
};

export type GetMusicByIdLyricsFuriganaErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdLyricsFuriganaError = GetMusicByIdLyricsFuriganaErrors[keyof GetMusicByIdLyricsFuriganaErrors];

export type GetMusicByIdLyricsFuriganaResponses = {
    /**
     * Furigana for each Japanese lyric line
     */
    200: LyricsFurigana;
};

export type GetMusicByIdLyricsFuriganaResponse = GetMusicByIdLyricsFuriganaResponses[keyof GetMusicByIdLyricsFuriganaResponses];

export type GetMusicByIdLyricsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/lyrics';
};

export type GetMusicByIdLyricsErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdLyricsError = GetMusicByIdLyricsErrors[keyof GetMusicByIdLyricsErrors];

export type GetMusicByIdLyricsResponses = {
    /**
     * The lyrics document, or null when the track has no lyrics
     */
    200: Lyrics;
};

export type GetMusicByIdLyricsResponse = GetMusicByIdLyricsResponses[keyof GetMusicByIdLyricsResponses];

export type PutMusicByIdLyricsData = {
    body?: Lyrics;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/lyrics';
};

export type PutMusicByIdLyricsErrors = {
    /**
     * Invalid lyrics document
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PutMusicByIdLyricsError = PutMusicByIdLyricsErrors[keyof PutMusicByIdLyricsErrors];

export type PutMusicByIdLyricsResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type PutMusicByIdLyricsResponse = PutMusicByIdLyricsResponses[keyof PutMusicByIdLyricsResponses];

export type GetMusicByIdLyricsTtmlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/lyrics/ttml';
};

export type GetMusicByIdLyricsTtmlErrors = {
    /**
     * Not found, or the track has no lyrics
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdLyricsTtmlError = GetMusicByIdLyricsTtmlErrors[keyof GetMusicByIdLyricsTtmlErrors];

export type GetMusicByIdLyricsTtmlResponses = {
    /**
     * TTML document
     */
    200: string;
};

export type GetMusicByIdLyricsTtmlResponse = GetMusicByIdLyricsTtmlResponses[keyof GetMusicByIdLyricsTtmlResponses];

export type DeleteMusicByIdVocalsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/vocals';
};

export type DeleteMusicByIdVocalsErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdVocalsError = DeleteMusicByIdVocalsErrors[keyof DeleteMusicByIdVocalsErrors];

export type DeleteMusicByIdVocalsResponses = {
    /**
     * Deleted, or there was none
     */
    204: void;
};

export type DeleteMusicByIdVocalsResponse = DeleteMusicByIdVocalsResponses[keyof DeleteMusicByIdVocalsResponses];

export type GetMusicByIdVocalsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/vocals';
};

export type GetMusicByIdVocalsErrors = {
    /**
     * Not found, or the track has no vocal analysis
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdVocalsError = GetMusicByIdVocalsErrors[keyof GetMusicByIdVocalsErrors];

export type GetMusicByIdVocalsResponses = {
    /**
     * Vocal analysis
     */
    200: Blob | File;
};

export type GetMusicByIdVocalsResponse = GetMusicByIdVocalsResponses[keyof GetMusicByIdVocalsResponses];

export type PutMusicByIdVocalsData = {
    body?: Blob | File;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/vocals';
};

export type PutMusicByIdVocalsErrors = {
    /**
     * Empty body
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
    /**
     * Larger than 8388608 bytes
     */
    413: {
        message: string;
    };
};

export type PutMusicByIdVocalsError = PutMusicByIdVocalsErrors[keyof PutMusicByIdVocalsErrors];

export type PutMusicByIdVocalsResponses = {
    /**
     * Stored
     */
    200: Music;
};

export type PutMusicByIdVocalsResponse = PutMusicByIdVocalsResponses[keyof PutMusicByIdVocalsResponses];

export type GetMusicByIdDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/download';
};

export type GetMusicByIdDownloadErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetMusicByIdDownloadError = GetMusicByIdDownloadErrors[keyof GetMusicByIdDownloadErrors];

export type GetMusicByIdDownloadResponses = {
    /**
     * Audio stream
     */
    200: Blob | File;
};

export type GetMusicByIdDownloadResponse = GetMusicByIdDownloadResponses[keyof GetMusicByIdDownloadResponses];

export type DeleteMusicByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}';
};

export type DeleteMusicByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteMusicByIdError = DeleteMusicByIdErrors[keyof DeleteMusicByIdErrors];

export type DeleteMusicByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteMusicByIdResponse = DeleteMusicByIdResponses[keyof DeleteMusicByIdResponses];

export type PatchMusicByIdData = {
    body?: UpdateMusicRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}';
};

export type PatchMusicByIdErrors = {
    /**
     * Invalid TTML lyrics
     */
    400: {
        message: string;
    };
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchMusicByIdError = PatchMusicByIdErrors[keyof PatchMusicByIdErrors];

export type PatchMusicByIdResponses = {
    /**
     * Updated
     */
    200: Music;
};

export type PatchMusicByIdResponse = PatchMusicByIdResponses[keyof PatchMusicByIdResponses];

export type PatchMusicReorderData = {
    body?: MusicReorderRequest;
    path?: never;
    query?: never;
    url: '/music/reorder';
};

export type PatchMusicReorderErrors = {
    /**
     * Invalid order
     */
    400: {
        message: string;
    };
};

export type PatchMusicReorderError = PatchMusicReorderErrors[keyof PatchMusicReorderErrors];

export type PatchMusicReorderResponses = {
    /**
     * Order updated
     */
    200: Array<Music>;
};

export type PatchMusicReorderResponse = PatchMusicReorderResponses[keyof PatchMusicReorderResponses];

export type GetAppConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app/config';
};

export type GetAppConfigResponses = {
    /**
     * Runtime configuration
     */
    200: AppConfig;
};

export type GetAppConfigResponse = GetAppConfigResponses[keyof GetAppConfigResponses];

export type PatchAppConfigData = {
    body?: AppConfigUpdate;
    path?: never;
    query?: never;
    url: '/app/config';
};

export type PatchAppConfigErrors = {
    /**
     * Invalid configuration
     */
    400: {
        message: string;
    };
};

export type PatchAppConfigError = PatchAppConfigErrors[keyof PatchAppConfigErrors];

export type PatchAppConfigResponses = {
    /**
     * Updated runtime configuration
     */
    200: AppConfigUpdateResponse;
};

export type PatchAppConfigResponse = PatchAppConfigResponses[keyof PatchAppConfigResponses];

export type PostMusicByIdPlaysData = {
    body?: PlayEventRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/music/{id}/plays';
};

export type PostMusicByIdPlaysErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
    /**
     * Session belongs to another track
     */
    409: {
        message: string;
    };
};

export type PostMusicByIdPlaysError = PostMusicByIdPlaysErrors[keyof PostMusicByIdPlaysErrors];

export type PostMusicByIdPlaysResponses = {
    /**
     * Recorded
     */
    200: PlayEventResponse;
};

export type PostMusicByIdPlaysResponse = PostMusicByIdPlaysResponses[keyof PostMusicByIdPlaysResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
        /**
         * Client Date#getTimezoneOffset()
         */
        tzOffsetMinutes?: number | null;
        limit?: number;
    };
    url: '/stats';
};

export type GetStatsResponses = {
    /**
     * Listening statistics
     */
    200: ListeningStats;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];
