/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToPlaylistDialog: typeof import('./components/AddToPlaylistDialog.vue')['default']
    AudoriaLogo: typeof import('./components/AudoriaLogo.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoloCoverArt: typeof import('./components/HoloCoverArt.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    InputPromptDialog: typeof import('./components/InputPromptDialog.vue')['default']
    LazyCoverImage: typeof import('./components/LazyCoverImage.vue')['default']
    MetadataEditDialog: typeof import('./components/MetadataEditDialog.vue')['default']
    ParallaxCard: typeof import('./components/ParallaxCard.vue')['default']
    PlayerBar: typeof import('./components/PlayerBar.vue')['default']
    PlaylistCover: typeof import('./components/PlaylistCover.vue')['default']
    ProgressPreviewTooltip: typeof import('./components/ProgressPreviewTooltip.vue')['default']
    QueueDrawer: typeof import('./components/QueueDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShaderProgressBar: typeof import('./components/ShaderProgressBar.vue')['default']
    ShaderProgressControls: typeof import('./components/ShaderProgressControls.vue')['default']
    SoundWave: typeof import('./components/SoundWave.vue')['default']
  }
}
